<div class="sheet">
	<h2>Contactpersoon <?php echo $contactpersoon->id ? 'Toevoegen' : 'Bewerken' ?></h2>
	
	<form
		method="post"
		action="<?= $this->router->link('Administratie_Contactpersoon_Controller', 'contactpersoon_toevoegen', $bedrijf->id, $contactpersoon->id) ?>"
		accept-charset="utf-8">

		<?= $this->form->origin() ?>

		<p>
			<label>naam:</label>
			<?= $this->form->textfield('voornaam', $contactpersoon->voornaam, $errors)->set_placeholder('voornaam') ?>
			<?= $this->form->textfield('achternaam', $contactpersoon->achternaam, $errors)->set_placeholder('achternaam') ?>
		</p>
		
		<br>
		
		<p>
			<label for="telefoon">telefoonnr:</label>
			<?= $this->form->textfield('telefoon', $contactpersoon->telefoon, $errors) ?>
		</p>
		
		<p>
			<label for="emailadres">emailadres</label>
			<?= $this->form->textfield('emailadres', $contactpersoon->emailadres, $errors)->set_size(30) ?>
		</p>
	
		<br>
	
		<p>
			<label>adres:</label>
			<span style="display: inline-block">
			<?= $this->form->textfield('straatnaam', $contactpersoon->straatnaam, $errors)->set_placeholder('straatnaam') ?>
			<?= $this->form->textfield('huisnummer', $contactpersoon->huisnummer, $errors)->set_size(3)->set_placeholder('nr') ?>
			<br>
			<?= $this->form->textfield('postcode', $contactpersoon->postcode, $errors)->set_placeholder('postcode')->set_size(6) ?>
			<?= $this->form->textfield('plaats', $contactpersoon->plaats, $errors)->set_placeholder('plaatsnaam') ?>
			</span>
		</p>
		
		<p>
			<?= $this->form->checkbox('ontvangt_factuur', $contactpersoon->ontvangt_factuur, $errors) ?>
			<label class="for-checkbox" for="ontvangt_factuur">deze persoon ontvangt de facturen</label>
		</p>
		
		<p class="controls">
			<?php if ($contactpersoon->is_deletable): ?>
				<button type="submit" name="delete" value="yes" class="delete">Verwijderen</button>
			<?php endif ?>
			
			<?php if ($contactpersoon->id): ?>
				<button type="submit">Opslaan</button>
			<?php else: ?>
				<button type="submit">Contactperoon Toevoegen</button>
			<?php endif ?>
			
			<button onclick="hide_sheet(this); return false">Sluiten</button>
		</p>
	</form>
</div>