<div class="sheet">
	<h2>Factuur aanmaken</h2>
	
	<form
		method="post"
		action="<?= $this->router->link('Administratie_Factuur_Controller', 'factuur_toevoegen', $bedrijf->id, $factuur->id) ?>"
		accept-charset="utf-8">
		
		<?= $this->form->origin() ?>
		
		<p>
			<label for="project_naam">Projectnaam:</label>
			<?= $this->form->textfield('project_naam', $factuur->project_naam, $errors)->add_class('wide') ?>
		</p>
	
		<p>
			<label for="project_beschrijving">Omschrijving:</label>
			<?= $this->form->textarea('project_beschrijving', $factuur->project_beschrijving, $errors) ?>
		</p>
		
		<?php if ($factuur->is_new): ?>
		<p>
			<label for="verzend_datum">Verzenddatum:</label>
			<?= $this->form->datepicker('verzend_datum', $factuur->verzend_datum, $errors) ?>
		</p>
		<?php endif ?>
		
		<p>
			<label for="uiterste_betaal_datum">Uiterste datum van betaling:</label>
			<?= $this->form->datepicker('uiterste_betaal_datum', $factuur->uiterste_betaal_datum, $errors) ?>
		</p>

		<?php if ($uren): ?>
		
		<div class="urenselector">
		<?php
			$this->views->from_record($this->uren)
				->set_data($uren)
				->add_column('id', '', IHG_HTML_Table::checkbox_decorator('uur'))
				->add_column('beschrijving', 'Beschrijving', 'summary')
				->add_column('start_tijd', 'Datum', new IHG_Formatter_Date())
				->add_column('duur', 'Duur', function($aantal) { return number_format($aantal, 1); })
				->add_column('prijs', 'Prijs', new IHG_Formatter_Price())
				->draw();
		?>
		</div>
		
		<div class="drag-resize-handle" data-target-node=".urenselector"></div>
	
		<?php endif ?>
	
		<p class="controls">
			<?php if ($factuur->is_deletable): ?>
				<button type="submit" class="delete" name="delete" value="yes">Verwijderen</button>
			<?php endif ?>
			
			<?php if ($factuur->is_new): ?>
				<button type="submit" class="default">Factuur aanmaken</button>
			<?php else: ?>
				<button type="submit" class="default">Opslaan</button>
			<?php endif ?>
			<button onclick="hide_sheet(this); return false">Sluiten</button>
		</p>
	</form>
</div>