<h2>
	Factuur <?=$this->_html($factuur->nummer)?>
	<small><?= $this->_link_sheet('bewerken', 'Administratie_Factuur_Controller', 'factuur_toevoegen', $factuur->bedrijf_id, $factuur->id) ?></small>
</h2>

<?php if ($factuur->start_tijd && $factuur->eind_tijd): ?>
<h5><?=$factuur->start_tijd->format('d/m/Y h:i')?> tot <?=$factuur->eind_tijd->format('d/m/Y h:i')?></h5>
<?php endif ?>

<div class="span-6">
	<table class="prijs">
		<tr>
			<th>Prijs:</th>
			<td><?=$this->_format_price($factuur->prijs)?></td>
		</tr>
		<tr>
			<th>BTW: <?=$factuur->btw_tarief->percentage * 100?>%</th>
			<td><?=$this->_format_price($factuur->btw)?></td>
		</tr>
		<tr class="summary">
			<th>Totaal:</th>
			<td><?=$this->_format_price($factuur->prijs_incl)?></td>
		</tr>
	</table>
	
	<p><strong>Geadresseerde:</strong> <?=nl2br($this->_html($factuur->contactpersoon->adres))?></p>
	
	<p><strong>Verzenddatum:</strong> <?=$this->_format_date($factuur->verzend_datum)?><br>
	Uiterste betaaldatum: <?=$this->_format_date($factuur->uiterste_betaal_datum)?><br>
	Voldaan: <?=$factuur->voldaan ? 'Ja' : ($factuur->termijn_resterend > 0 ? ('Nee (' . $factuur->termijn_resterend . ' dagen)') : '<span class="FAIL">Nee</span>')?> <?=$this->_link_sheet('bewerken', 'Administratie_Factuur_Controller', 'factuur_voldaan', $factuur->id)?></p>

        <p><a href="<?=$this->router->link('Administratie_Factuur_Controller', 'factuur_pdf', $factuur->id)?>" target="_new">Exporteer naar PDF</a></p>
</div>
<div class="span-18 last">
	<p><strong><?=$this->_inline_edit(
		$this->router->link('Administratie_Factuur_Controller', 'post_project_naam', $factuur->id),
		$factuur->project_naam)?></strong><br>
		<?=$this->_inline_edit(
			$this->router->link('Administratie_Factuur_Controller', 'post_project_beschrijving', $factuur->id),
			$factuur->project_beschrijving) ?>
	</p>
	<?/*=$this->_partial('Administratie_Uur_Controller', 'factuur', $factuur->id)*/?>
	<?=$this->_partial('Administratie_Aankoop_Controller', 'factuur', $factuur->id)?>
</div>