<div class="sheet">
	<h2>Factuur aanmaken</h2>
	
	<form
		method="post"
		action="<?= $this->router->link('Administratie_Factuur_Controller', 'factuur_toevoegen', $bedrijf->id, $factuur->id) ?>"
		accept-charset="utf-8">
		
		<?= $this->form->origin() ?>
		
		<p>
			<label for="project_naam">projectnaam:</label>
			<?= $this->form->textfield('project_naam', $factuur->project_naam, $errors)->add_class('wide') ?>
		</p>
	
		<p>
			<label for="project_beschrijving">beschrijving:</label>
			<?= $this->form->textarea('project_beschrijving', $factuur->project_beschrijving, $errors) ?>
		</p>
		
		<?php if ($factuur->is_new): ?>
		<p>
			<label for="verzend_datum">verzend datum:</label>
			<?= $this->form->datepicker('verzend_datum', $factuur->verzend_datum, $errors) ?>
		</p>
		<?php endif ?>
		
		<p>
			<label for="uiterste_betaal_datum">uiterste datum van betaling:</label>
			<?= $this->form->datepicker('uiterste_betaal_datum', $factuur->uiterste_betaal_datum, $errors) ?>
		</p>

		<?php if ($uren): ?>
		
		<div id="urenselector">
		<?php
			$this->views->from_record($this->uren)
				->set_data($uren)
				->add_column('id', '', IHG_HTML_Table::checkbox_decorator('uur'))
				->add_column('beschrijving', 'Beschrijving', 'summary')
				->add_column('start_tijd', 'Datum', create_function('$x', 'return $x->format("d-m-Y");'))
				->add_column('duur', 'Duur')
				->add_column('prijs', 'Prijs', create_function('$x', 'return "&euro;" . number_format($x, 2, ",", ".");'))
				->draw();
		?>
		</div>
		
		<div class="drag-resize-handle" data-target-node="urenselector"></div>
	
		<?php endif ?>
	
		<p class="controls">
			<?php if ($factuur->is_deletable): ?>
				<button type="submit" class="delete" name="delete" value="yes">Verwijderen</button>
			<?php endif ?>
			
			<?php if ($factuur->is_new): ?>
				<button type="submit" class="default">Factuur Aanmaken</button>
			<?php else: ?>
				<button type="submit" class="default">Opslaan</button>
			<?php endif ?>
			<button onclick="hide_sheet(this); return false">Sluiten</button>
		</p>
	</form>
</div>